stages:
  - build
  - release
 
#################################
# Build the Windows MSI Installer
#################################
build:
  stage: build
  tags:
    - windows
    - windows-1809
  script:
    # Install python
    - choco install -y --no-progress python3 --version=3.9.2
    # Ensure Pip is on the path
    - $pydir = & py -3.9 -c "import sys,os;print(os.path.join(os.path.dirname(sys.executable),'Scripts'))"
    - $Env:path += ";$pydir"
    - Get-Command pip

    # Install WIX Toolkit
    - wget https://github.com/wixtoolset/wix3/releases/download/wix311rtm/wix311-binaries.zip -UseBasicParsing -OutFile c:\wix311-binaries.zip
    - mkdir c:\\wix311
    - Expand-Archive -Path c:\wix311-binaries.zip -DestinationPath c:\\wix311\\bin
    - $env:WIX="C:\\wix311\\"
    - $env:PYTHONIOENCODING="UTF-8"

    # Build app  
    - py -3.9 -m pip install -U pip==21.2.4 poetry==1.1.6  # newer pip ignores setup.py
    - py -3.9 -m poetry install

    - dir
    - echo $env:CI_PROJECT_URL/-/raw/$env:CI_COMMIT_SHA/python-3.9.2-embed-amd64-tkinter.zip
    - py -3.9 -m poetry run python setup.py windows --sanitize-version --build --template briefcase-template
    - dir windows
    - copy-item windows\\*.msi .\\
    - dir

  artifacts:
    name: "WSL-USB-GUI-$CI_COMMIT_SHORT_SHA"
    paths:
      - .\\*.msi
    expire_in: 3 days


########################################################################
# Upload the built installer to the tags page on Gitlab for the release
########################################################################
publish:
  stage: release
  image: python:3
  variables:
    GIT_STRATEGY: none
    GIT_SUBMODULE_STRATEGY: none
  script:
    - pip3 install gitlab-release
    - for f in ./*.msi; do mv "$f" "${f// /-}"; done
    - gitlab-release ./*.msi
  only:
    - tags
  artifacts:
    name: "WSL-USB-GUI-${CI_COMMIT_TAG}"
    expire_in: never
    paths:
      - ./*.msi
